version: '3.7'

services:
  web:
    image: nginx:1.12
    volumes:      
      - ./:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - php
    depends_on:
      - jenkins-exam2
      - php
    ports:
      - "8080:80"

  php:
    build:
      context: ./
      dockerfile: php_pdo.Dockerfile
    volumes:
      - ./:/var/www/html/
    depends_on:
      - jenkins-exam2

  jenkins-exam2:
    build:
      context: ./
      dockerfile: jenkins.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8091:80"
