version: '3.7'

services:
  web:
    image: nginx:1.12
    volumes:      
      - ./:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - php
    depends_on:
      - php
    ports:
      - "8093:80"

  php:
    build:
      context: ./
      dockerfile: php_pdo.Dockerfile
    volumes:
      - ./:/var/www/html/

  db:
    image: mariadb:10.1
    volumes:
      - ./bdd/docker/mariadb:/docker-entrypoint-initdb.d/
      - ./bdd/var/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'php_user'
      MYSQL_PASSWORD: 'sdrugntqqsciur'
    ports:
      - '3306:3306'
    command:
      'mysqld --innodb-flush-method=fsync'